# Generated by Django 5.2.5 on 2025-09-26 04:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institution_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Institution logo (optional)'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Company logo (optional)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Project screenshot (optional)'),
        ),
    ]
