# Generated by Django 5.2.5 on 2025-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("leetcode", "LeetCode"),
                    ("codeforces", "Codeforces"),
                    ("kaggle", "Kaggle"),
                    ("website", "Personal Website"),
                    ("twitter", "Twitter"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                ],
                help_text="Social media platform or website name",
                max_length=20,
            ),
        ),
    ]
