# Generated by Django 5.2.5 on 2025-08-26 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date', 'order'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', 'order'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Information'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text="Visitor's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text="Visitor's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, help_text='Mark as read'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(help_text='Message subject', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='achievements',
            field=models.TextField(blank=True, help_text='Academic achievements and honors'),
        ),
        migrations.AlterField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False, help_text='Currently studying here'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='Degree obtained', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the program'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date (leave blank if current)', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(help_text='Field of study/major', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA (0.00-4.00 scale, optional)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='Educational institution name', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(help_text='Start date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, help_text='Key achievements and accomplishments'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(help_text='Company name', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False, help_text='Currently working here'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Job description and responsibilities'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date (leave blank if current)', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, help_text='Work location (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(help_text='Job title/position', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(help_text='Start date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this role', related_name='experiences', to='portfolio_api.skill'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='bio',
            field=models.TextField(help_text='Professional biography or summary'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(help_text='Primary email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL (optional)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL (optional)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(help_text='Full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (optional)', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture (optional)', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume/CV file (optional)', upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='title',
            field=models.CharField(help_text='Professional title or role', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL (optional)'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='website',
            field=models.URLField(blank=True, help_text='Personal website URL (optional)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as featured project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL (optional)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project screenshot (optional)', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live demo URL (optional)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Brief project summary', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(help_text='Technologies used', related_name='projects', to='portfolio_api.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('database', 'Databases'), ('tool', 'Tools & Technologies'), ('soft', 'Soft Skills'), ('cloud', 'Cloud & DevOps'), ('design', 'Design & UI/UX')], help_text='Skill category', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Skill description (optional)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class (FontAwesome, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Skill name', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], default=5, help_text='Proficiency level from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
