# Generated by Django 5.2.5 on 2025-09-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0002_alter_sociallink_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="institution_logo",
            field=models.ImageField(
                blank=True,
                help_text="Institution logo (recommended size: 100x100px, transparent background)",
                null=True,
                upload_to="institution_logos/",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo (recommended size: 100x100px, transparent background)",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
