# Generated by Django 5.2.5 on 2025-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0003_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="profile_image",
            field=models.CharField(
                default="assets/images/profile_pic.png",
                help_text="Path in static files",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="resume",
            field=models.CharField(
                default="assets/docs/resume.pdf",
                help_text="Path in static files",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Project screenshot (optional)",
                upload_to="media/projects/",
            ),
        ),
    ]
