# Generated by Django 5.2.5 on 2025-09-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0004_alter_personalinfo_profile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="twitter",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="leetcode",
            field=models.URLField(
                blank=True, help_text="LeetCode profile URL (optional)"
            ),
        ),
    ]
