# Generated by Django 5.2.5 on 2025-09-15 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_api", "0005_remove_personalinfo_twitter_personalinfo_leetcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="gpa",
        ),
        migrations.AddField(
            model_name="education",
            name="cpi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="CPI (0.00-10.00 scale, optional)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
    ]
